---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devingardner.
--- DateTime: 3/5/24 12:32 PM
---
fs.delete("refresh.lua")
shell.run("wget https://raw.githubusercontent.com/devmgardner/projects_misc/master/minecraft/cc_tweaked/spawner/refresh_spawner_scripts.lua refresh.lua")