---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devingardner.
--- DateTime: 3/3/24 10:25 AM
---
fs.delete("startup/sorter.lua")
shell.run("wget https://raw.githubusercontent.com/devmgardner/projects_misc/master/minecraft/cc_tweaked/sorter/sorter.lua startup/sorter.lua")
