---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devingardner.
--- DateTime: 4/25/24 1:14PM
---

-- need to create while loop
-- while True, check contents of connected inventory (var name: "input_inv")
local input_inv = peripheral.find("compactstorage:compact_chest")
local affix_inv = peripheral.find("storagedrawers:controller")
local normal_inv = peripheral.find("storagedrawers:controller_slave")
-- if items in input_inv, iterate over all items
-- if input_inv.getItemDetail(<item slot #>) has key 'lore', send to another connected inventory (var name: "affix_inv")
-- else, send to regular connected inventory (var name: "normal_inv")
-- need to find good "refresh rate" for the while loop
while(true) do
    input_inv_list = input_inv.list()
    if #input_inv_list > 0 then
        for slot, item in pairs(input_inv.list()) do
            local this_item = input_inv.getItemDetail(slot)
            if this_item['lore'] ~= nil then
                input_inv.pushItems(peripheral.getName(affix_inv), slot)
            else
                input_inv.pushItems(peripheral.getName(normal_inv), slot)
            end
        end
    else
        sleep(0.2)
    end
    sleep(0.2)
end
