---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devingardner.
--- DateTime: 4/25/24 1:14PM
---

--local dev_func = require("dev_func")
--dev_func.clearMon(monitor)

-- need to create while loop
-- while True, check contents of connected inventory (var name: "input_inv")
local input_inv = peripheral.wrap("compactstorage:compact_chest")
local affix_inv = peripheral.find("storagedrawers:controller")
local normal_inv = peripheral.wrap("storagedrawers:controller_slave")
-- if items in input_inv, iterate over all items
-- if input_inv.getItemDetail(<item slot #>) has key 'lore', send to another connected inventory (var name: "affix_inv")
-- else, send to regular connected inventory (var name: "normal_inv")
-- need to find good "refresh rate" for the while loop
while(true)
    do

end
