---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devingardner.
--- DateTime: 3/3/24 10:25 AM
---
fs.delete("spawner.lua")
fs.delete("start_all.lua")
fs.delete("end_all.lua")
fs.delete("dev_func.lua")
fs.delete("startup/startup.lua")
shell.run("wget https://raw.githubusercontent.com/devmgardner/projects_misc/master/minecraft/cc_tweaked/spawner.lua spawner.lua")
shell.run("wget https://raw.githubusercontent.com/devmgardner/projects_misc/master/minecraft/cc_tweaked/start_all.lua start_all.lua")
shell.run("wget https://raw.githubusercontent.com/devmgardner/projects_misc/master/minecraft/cc_tweaked/end_all.lua end_all.lua")
shell.run("wget https://raw.githubusercontent.com/devmgardner/projects_misc/master/minecraft/cc_tweaked/dev_func.lua dev_func.lua")
shell.run("wget https://raw.githubusercontent.com/devmgardner/projects_misc/master/minecraft/cc_tweaked/startup.lua startup/startup.lua")
