---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devingardner.
--- DateTime: 3/5/24 12:42 PM
---

monitor = peripheral.find("monitor")
monitor.setTextScale(0.5)
local dev_func = require("dev_func")

dev_func.clearMon(monitor)
dev_func.showHelp(monitor)

return
