---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by devin gardner.
--- DateTime: 5/7/2024 9:24 PM
---

local modem = peripheral.find("modem")
modem.open(43)
local controller = peripheral.find("storagedrawers:controller")

function sendCounts(mod, con)
    local result = 0
    for _, item in pairs(con.list()) do
        if item['count'] ~= nil then
            result = result + item['count']
        end
    end
    mod.transmit(43, 43, result)
end


while(true) do
    sendCounts(modem, controller)
    sleep(5)
end
